/** Kit reason-code mirror (consume, do not fork a second writer). */

export const WORKFLOW_ROUTE_DEFERRED = "WORKFLOW_ROUTE_DEFERRED";
export const WORKFLOW_LOOP_CAP = "WORKFLOW_LOOP_CAP";
export const FIX_FAILED = "FIX_FAILED";
export const BLOCK_RETRY_CAP_EXHAUSTED = "BLOCK_RETRY_CAP_EXHAUSTED";
export const RELEASE_TESTS_FAILED = "RELEASE_TESTS_FAILED";
export const RELEASE_QA_MISSING = "RELEASE_QA_MISSING";
export const RELEASE_UAT_FAILED = "RELEASE_UAT_FAILED";
export const RELEASE_ARTIFACTS_MISSING = "RELEASE_ARTIFACTS_MISSING";
export const RELEASE_PREMATURE = "RELEASE_PREMATURE";
export const CLOSURE_RELEASE_EVIDENCE_MISSING = "CLOSURE_RELEASE_EVIDENCE_MISSING";
export const RECOVERY_FALSE_COMPLETION = "RECOVERY_FALSE_COMPLETION";
export const RESUME_BRIEF_STALE = "RESUME_BRIEF_STALE";
export const KERNEL_VALIDATOR_MISSING = "KERNEL_VALIDATOR_MISSING";
export const WORK_KIND_DELIVERY_MODE_CONFLICT = "WORK_KIND_DELIVERY_MODE_CONFLICT";
export const WORK_KIND_ROUTING_OFF = "WORK_KIND_ROUTING_OFF";
export const DELIVERY_MODE_SWITCH_MID_STORY = "DELIVERY_MODE_SWITCH_MID_STORY";
export const DELIVERY_MODE_INELIGIBLE = "DELIVERY_MODE_INELIGIBLE";
export const MEGA_QUICK_BUG_SEGMENT = "MEGA_QUICK_BUG_SEGMENT";
export const MEGA_QUICK_AC_TOO_BROAD = "MEGA_QUICK_AC_TOO_BROAD";
export const MEGA_QUICK_ARCHITECTURE_REQUIRED = "MEGA_QUICK_ARCHITECTURE_REQUIRED";
export const MEGA_QUICK_SPRINT_EXISTS = "MEGA_QUICK_SPRINT_EXISTS";
export const MEGA_QUICK_STORY_OVERRIDE = "MEGA_QUICK_STORY_OVERRIDE";
export const MEGA_QUICK_MULTI_COMPONENT = "MEGA_QUICK_MULTI_COMPONENT";
export const MEGA_QUICK_GATE_ESCALATION = "MEGA_QUICK_GATE_ESCALATION";
/** AC-6 terminals — non-relaxable even under AUTONOMY_PRESET=full. */
export const DECISION_UNRESOLVED = "DECISION_UNRESOLVED";
export const KERNEL_INCOMPATIBLE = "KERNEL_INCOMPATIBLE";
export const QUALITY_EVIDENCE_FAILED = "QUALITY_EVIDENCE_FAILED";
export const BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED";
export const RESUME_AMBIGUOUS = "RESUME_AMBIGUOUS";

export const AC6_NONRELAXABLE_TERMINALS = [
	DECISION_UNRESOLVED,
	KERNEL_INCOMPATIBLE,
	QUALITY_EVIDENCE_FAILED,
	BUDGET_EXHAUSTED,
	RESUME_AMBIGUOUS,
] as const;

export const MEGA_QUICK_CODES = [
	MEGA_QUICK_BUG_SEGMENT,
	MEGA_QUICK_AC_TOO_BROAD,
	MEGA_QUICK_ARCHITECTURE_REQUIRED,
	MEGA_QUICK_SPRINT_EXISTS,
	MEGA_QUICK_STORY_OVERRIDE,
	MEGA_QUICK_MULTI_COMPONENT,
	MEGA_QUICK_GATE_ESCALATION,
] as const;

export const STOP_REASONS = [
	"completed",
	"decision_gate",
	"missing_input",
	"pause_request",
	"loop_max",
	"error",
	"blocked",
] as const;

export type StopReason = (typeof STOP_REASONS)[number];
