export const POLICY_DEFAULT_DENY = "POLICY_DEFAULT_DENY";
export const POLICY_RAW_PI_TOOL_DENIED = "POLICY_RAW_PI_TOOL_DENIED";
export const POLICY_STUB_TOOL_DENIED = "POLICY_STUB_TOOL_DENIED";
export const POLICY_TRAVERSAL_DENIED = "POLICY_TRAVERSAL_DENIED";
export const POLICY_PO_PRODUCTION_WRITE = "POLICY_PO_PRODUCTION_WRITE";
export const POLICY_QA_SILENT_FIX = "POLICY_QA_SILENT_FIX";
export const POLICY_RELEASE_CLOSURE_WRITE = "POLICY_RELEASE_CLOSURE_WRITE";
export const POLICY_CLOSURE_RELEASE_WRITE = "POLICY_CLOSURE_RELEASE_WRITE";
export const POLICY_CURATOR_INTENT_REWRITE = "POLICY_CURATOR_INTENT_REWRITE";
export const POLICY_SECRET_PATH_DENIED = "POLICY_SECRET_PATH_DENIED";
export const POLICY_SHELL_UNPARSEABLE = "POLICY_SHELL_UNPARSEABLE";
export const POLICY_SHELL_EXFIL_DENIED = "POLICY_SHELL_EXFIL_DENIED";
export const POLICY_SHELL_PRIVILEGED_DENIED = "POLICY_SHELL_PRIVILEGED_DENIED";
export const POLICY_SHELL_DESTRUCTIVE_DENIED = "POLICY_SHELL_DESTRUCTIVE_DENIED";
export const POLICY_PACKAGE_DENIED = "POLICY_PACKAGE_DENIED";
export const POLICY_GIT_FORCE_DENIED = "POLICY_GIT_FORCE_DENIED";
export const ISOLATION_BACKEND_UNAVAILABLE = "ISOLATION_BACKEND_UNAVAILABLE";
export const POLICY_ASK_UNAPPROVED = "POLICY_ASK_UNAPPROVED";
export const SESSION_ORCHESTRATOR_TOOLS_DENIED = "SESSION_ORCHESTRATOR_TOOLS_DENIED";
export const AUTO_ORCHESTRATOR_PHASE_EXECUTION = "AUTO_ORCHESTRATOR_PHASE_EXECUTION";

export class PolicyEngineError extends Error {
	readonly code: string;

	constructor(code: string, message?: string) {
		super(message ?? code);
		this.name = "PolicyEngineError";
		this.code = code;
	}
}
