export const PHASE_ROLE_MISMATCH = "PHASE_ROLE_MISMATCH";
export const PHASE_ROLE_CAPABILITY_MISSING = "PHASE_ROLE_CAPABILITY_MISSING";
export const RUNTIME_PROOF_MISSING = "RUNTIME_PROOF_MISSING";
export const RUNTIME_PROOF_STALE = "RUNTIME_PROOF_STALE";
export const RUNTIME_PROOF_INVALID = "RUNTIME_PROOF_INVALID";
export const PHASE_CONTEXT_ISOLATION_VIOLATION = "PHASE_CONTEXT_ISOLATION_VIOLATION";
export const AUTO_ORCHESTRATOR_PHASE_EXECUTION = "AUTO_ORCHESTRATOR_PHASE_EXECUTION";
export const CROSS_MODEL_DEGRADED_MODE = "CROSS_MODEL_DEGRADED_MODE";

export const SESSION_REUSED_ACROSS_PHASE = "SESSION_REUSED_ACROSS_PHASE";
export const SESSION_CONTINUATION_DENIED = "SESSION_CONTINUATION_DENIED";
export const SESSION_TRANSCRIPT_CARRYOVER = "SESSION_TRANSCRIPT_CARRYOVER";
export const SESSION_UNKNOWN_PHASE = "SESSION_UNKNOWN_PHASE";
export const SESSION_UNKNOWN_ROLE = "SESSION_UNKNOWN_ROLE";
export const SESSION_ORCHESTRATOR_TOOLS_DENIED = "SESSION_ORCHESTRATOR_TOOLS_DENIED";
export const ATTESTATION_MISSING = "ATTESTATION_MISSING";
export const ATTESTATION_HASH_MISMATCH = "ATTESTATION_HASH_MISMATCH";
export const ATTESTATION_KERNEL_SESSION_MISMATCH = "ATTESTATION_KERNEL_SESSION_MISMATCH";

export class RoleRuntimeError extends Error {
	readonly code: string;

	constructor(code: string, message?: string) {
		super(message ?? code);
		this.name = "RoleRuntimeError";
		this.code = code;
	}
}
