import type { KitProof, SidecarAttestation } from "./attestation.ts";
import {
	assertKitProof,
	assertSidecarPresent,
	attachStandaloneAttestation,
	attestationJsonlPath,
	canonicalJson,
	computeAttestationHash,
	sha256Canonical,
	stubContextPackHash,
	stubPolicyHash,
	verifyAttestationHash,
	withAttestationHash,
} from "./attestation.ts";
import type {
	PhaseCatalogEntry,
	RoleCatalog,
	RoleCatalogEntry,
	RoleMutability,
} from "./catalog.ts";
import {
	AUTO_ROLE_KEYS,
	BOUNDED_MANIFEST_KEYS,
	createDefaultRoleCatalog,
	resolvePhaseRole,
} from "./catalog.ts";
import {
	ATTESTATION_HASH_MISMATCH,
	ATTESTATION_KERNEL_SESSION_MISMATCH,
	ATTESTATION_MISSING,
	AUTO_ORCHESTRATOR_PHASE_EXECUTION,
	CROSS_MODEL_DEGRADED_MODE,
	PHASE_CONTEXT_ISOLATION_VIOLATION,
	PHASE_ROLE_CAPABILITY_MISSING,
	PHASE_ROLE_MISMATCH,
	RoleRuntimeError,
	RUNTIME_PROOF_INVALID,
	RUNTIME_PROOF_MISSING,
	RUNTIME_PROOF_STALE,
	SESSION_CONTINUATION_DENIED,
	SESSION_ORCHESTRATOR_TOOLS_DENIED,
	SESSION_REUSED_ACROSS_PHASE,
	SESSION_TRANSCRIPT_CARRYOVER,
	SESSION_UNKNOWN_PHASE,
	SESSION_UNKNOWN_ROLE,
	SOVEREIGN_BOOTSTRAP_DELIVERY_FAILED,
} from "./errors.ts";
import type { AgentKernel, KernelSession, OwnedToolDefinition } from "./kernel-port.ts";
import {
	assertNoOrchestratorPhaseWrite,
	assertOrchestratorSchedulingOnly,
	ORCHESTRATOR_DENIED_TOOLS,
} from "./orchestrator-gate.ts";
import { createSessionSupervisor, SessionSupervisor } from "./supervisor.ts";
import type {
	BootstrapAck,
	ContinuationContract,
	SessionSupervisorOptions,
	SpawnBootstrap,
	SpawnRequest,
	SupervisedSession,
} from "./types.ts";

export type {
	AgentKernel,
	ContinuationContract,
	KernelSession,
	KitProof,
	OwnedToolDefinition,
	PhaseCatalogEntry,
	RoleCatalog,
	RoleCatalogEntry,
	RoleMutability,
	SessionSupervisorOptions,
	SidecarAttestation,
	SpawnBootstrap,
	BootstrapAck,
	SpawnRequest,
	SupervisedSession,
};

export {
	assertKitProof,
	assertNoOrchestratorPhaseWrite,
	assertOrchestratorSchedulingOnly,
	assertSidecarPresent,
	ATTESTATION_HASH_MISMATCH,
	ATTESTATION_KERNEL_SESSION_MISMATCH,
	ATTESTATION_MISSING,
	attestationJsonlPath,
	attachStandaloneAttestation,
	AUTO_ORCHESTRATOR_PHASE_EXECUTION,
	AUTO_ROLE_KEYS,
	BOUNDED_MANIFEST_KEYS,
	canonicalJson,
	computeAttestationHash,
	createDefaultRoleCatalog,
	createSessionSupervisor,
	CROSS_MODEL_DEGRADED_MODE,
	ORCHESTRATOR_DENIED_TOOLS,
	PHASE_CONTEXT_ISOLATION_VIOLATION,
	PHASE_ROLE_CAPABILITY_MISSING,
	PHASE_ROLE_MISMATCH,
	resolvePhaseRole,
	RoleRuntimeError,
	RUNTIME_PROOF_INVALID,
	RUNTIME_PROOF_MISSING,
	RUNTIME_PROOF_STALE,
	SESSION_CONTINUATION_DENIED,
	SESSION_ORCHESTRATOR_TOOLS_DENIED,
	SESSION_REUSED_ACROSS_PHASE,
	SESSION_TRANSCRIPT_CARRYOVER,
	SESSION_UNKNOWN_PHASE,
	SESSION_UNKNOWN_ROLE,
	SOVEREIGN_BOOTSTRAP_DELIVERY_FAILED,
	SessionSupervisor,
	sha256Canonical,
	stubContextPackHash,
	stubPolicyHash,
	verifyAttestationHash,
	withAttestationHash,
};
